FROM python:3.12

WORKDIR /workspace

RUN apt-get update && apt-get install -y --no-install-recommends \
    git openssh-client make vim iputils-ping \
    && rm -rf /var/lib/apt/lists/*

COPY requirements ./requirements
RUN pip install --upgrade pip && pip install -r requirements/dev.txt


COPY src /workspace/src

CMD ["uvicorn", "app.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000"]
