FROM python:3.12-slim

WORKDIR /app

COPY requirements/test.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY src /app

CMD ["pytest", "--maxfail=1", "--disable-warnings", "-q"]
